import React, { useState,} from 'react'
import {Loader, Card, FormField} from '../componenets';

// 4 - we started working on the home page
//10 - Then we create rendercards which takes a data and title if it detects some data we return map the entered into the data
// and render card jsx created 

const RenderCards = ({data, title}) => {
   if(data.length>0) {
    return data.map((post) => <Card key={post._id} {...post}/>)
   }
// If there is no data entered, return No search results found
   return (
   <h2 className="mt-5 font-bold text-[#6449ff] text-x1 uppercase">
    {title}
   </h2>
   )
}

const Home = () => {
// 7 - Created 3 states in which first is a varibales and set{VaribleName} is used for changing the state of it 
  const [loading, setLoading]  = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState('abc');

// 5 - Initially created a section in which we created a h1 and p which holds text
// 6 - Created a form field which initially renders just a text from it
// 8 - Here we access the loading state and check if it is true or not using ternary operator, if its true we render loader
// which gives us a loading gif
// 9 - If its false, which means it is rendering something and we check for the text entered by using searchText and render the text in a span
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p classname="mt-2 text-[#666e75] text-[16px] max-w[500px]">
          Browse through a collection of imaginative and visually stunnning images generated by Mid-Journery AI
        </p>
      </div>

      <div className="mt-16">
        <FormField/>
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader/>
            </div>
        ) : (
          <>
          {searchText && (
            <h2 className="font-medium text-[#666e75] text-xl mb-3">
              Showing results for <span className="text-[#222328]">
                {searchText}
              </span>
            </h2>
          )}
          <div className="grid lg:grid-cols-4 sm:grid-cols-3
          cs:grid-cols-2 grid-cols-1 gap-3">
          {searchText ?
          (
            <RenderCards
              data = {[]}
              title="No search results found" />
          ) : (
            <RenderCards 
            data={[]}
            title="No posts found" />
          )}

          </div>
          </>
        )}

      </div>

    </section>
  )
}

export default Home